import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ApolloWrapper from "@/app/ApolloWrapper";
import Navbar from "@/components/Navbar";



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Movie Sharing Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ApolloWrapper>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ApolloWrapper>
    
  )
}
